apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
type: Opaque
data:
  username: YmlsbGluZy1hcHA= #base64 для "billing-app"
  password: c2ltcGxlX3Bhc3N3b3Jk  #base64 для "simple_password"
  database: YmlsbGluZ19kYg== #base64 для billing_db